### PR TITLE
chore: auto update package version

### PR DESCRIPTION
**Pull request by imrishabh18**
1. It runs daily and checks for updates to the specified package.
2. If an update is available, it modifies the package.json and package-lock.json files.
3. It runs your project's tests to ensure the update doesn't break anything.
4. If the tests pass, it creates a pull request with the update.
5. The auto-merge action then attempts to merge this pull request into the main branch.

### CODE REVIEW

**Comment by seveibar** [comment]
So renovate seems to be doing this automatically, I'm a bit worried about having shell scripts (I usually do a `ts` + `bun` script whenever there's a complicated program)

One difference with renovate is it only runs for tscircuit packages which seems desirable.

image

**Comment by seveibar** [comment]
What if we tried modifying the renovate config so that it merges minor version updates? Until it's clear why renovate's broken I'm not sure we want to add a shell script that could be much harder to maintain- especially because this surface is difficult to test

Claude suggested modifying our renovate.json to allow minor version updates but I'm not totally sure it's actually broken.

Is the issue just that we're not publishing? I think we should do a deep dive here

```json
Updated Renovate Configuration

{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],
  "packageRules": [
    {
      "matchPackagePatterns": ["*"],
      "matchUpdateTypes": ["minor", "patch"],
      "automerge": true
    },
    {
      "matchPackagePatterns": ["*"],
      "matchUpdateTypes": ["major"],
      "automerge": false
    }
  ]
}
```

**Comment by imrishabh18** [comment]
Just saw in the closed PR's that renovate did make the update https://github.com/tscircuit/tscircuit/pull/348/files, but only to the lock file and not the package.json

**Comment by imrishabh18** [comment]
Seeing the closed PR's whenever the builder is updated, renovate is only updating the lock file and not the `package.json`. While for others, it updates both.

**Comment by seveibar** [comment]
That's so weird, i wonder why it's behaving like that

**Comment by seveibar** [comment]
Claude suggested `rangeStrategy` could be the issue:

image

**Comment by imrishabh18** [comment]
Okay, let me remove this and I will update the renovate config

**Comment by seveibar** [comment]
@imrishabh18 I'm almost positive that that's the issue 

image

image

**Pull request merged**
